### ISSUE TITLE
TripIt import blank page/fatal

### ISSUE THREAD

**Issue by reedy** [jpatokal/openflights#1178]
https://openflights.org/php/tripit_list_trips.php gives a HTTP 500

**Comment by reedy** [comment]
Don't get a blank page locally...

secrets.php missing post migration?

**Comment by rhaig** [comment]
this also logs the user out, which may be causing #1190

**Comment by semigator** [comment]
I’m seeing TripIt import fail with HTTP 500 on:
- https://openflights.org/php/tripit_rendezvous.php (500)
(also seeing %3Cscript%20defer%20src= requested and 404)

In DevTools > Network, the *response body* from tripit_rendezvous.php includes malformed HTML where a Cloudflare Insights script appears to be injected into an existing <script src="..."> attribute, e.g.:
<script type="text/javascript" src="<script defer src="https://static.cloudflareinsights.com/beacon.min.js ..."></script>

This causes the browser to try to fetch a URL literally starting with “%3Cscript%20defer%20src=” (404).
Blocking static.cloudflareinsights.com stops that 404 but the rendezvous.php request still returns 500.

Cookie note: PHPSESSID is present (e.g. rn9hdk0pua4l2pbondqaghjf2r).
Browsers tested: Chrome (143.0.7499.41), Windows (10.0.22000.3260).

**Comment by reedy** [comment]
https://github.com/jpatokal/openflights/issues/1502 also reported that, and was fixed in https://github.com/jpatokal/openflights/commit/48db9507bb562ed6bc009cde3f3a16fa3116f159

**Comment by semigator** [comment]
Thanks — I see the fix in 48db950 (adds require_once "helper.php" to tripit_rendezvous.php). 
[GitHub](https://github.com/jpatokal/openflights/commit/48db9507bb562ed6bc009cde3f3a16fa3116f159)

I’m still getting HTTP 500 on production: https://openflights.org/php/tripit_rendezvous.php
cf-ray: 9b4a254dde905c63-MIA date: Sat, 27 Dec 2025 16:20:31 GMT
Can you confirm whether 48db950 is deployed to openflights.org yet (and if there are multiple backends behind CF that need updating)?

**Comment by reedy** [comment]
It isn't deployed, and I don't have access to deploy, unfortunately.

**Comment by semigator** [comment]
Thanks, makes sense. Do you know who currently has access to deploy to openflights.org (or where to contact them)? Happy to provide additional logs if needed.

**Comment by DaveR66** [comment]
Thanks @reedy I guess it's up to @jpatokal now?

**Comment by reedy** [comment]
AFAIK, only @jpatokal has deployment access.

**Comment by jpatokal** [comment]
Apologies for the delay, the fix has been deployed.
